# https://starship.rs/
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """\
  $username\
  $hostname\
  $kubernetes\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $package\
  $dotnet\
  $golang\
  $java\
  $nodejs\
  $python\
  $ruby\
  $rust\
  $nix_shell\
  $memory_usage\
  $aws\
  $env_var\
  $cmd_duration\
  $line_break\
  $jobs\
  $battery\
  $time\
  $character\
"""

[directory]
truncation_length = 8
truncate_to_repo = false
use_logical_path = true
